// 全ページ共通の外側を作るファイル

// Metadataを持ってくる　Metadata→ Next.jsが用意している「ページ情報」の型。
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import style from './layout.module.css';
import Link from "next/link";
import { cookies } from "next/headers";
import { prisma } from "@/lib/prisma"
import LogoutButton from "@/components/LogoutButton";


// フォントを持ってくる
// Geistというフォントを使うための設定をして、その設定を geistSans という変数に保存している。
const geistSans = Geist({
  // フォントをCSSで使うための名前を設定
  variable: "--font-geist-sans",
  // Latin文字を対象にする
  subsets: ["latin"],
});

// Geist Monoというフォントの設定を作って、geistMono という変数に保存している。
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Webページの「ページ情報」を設定している部分
// このWebページの基本的な情報を設定している
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// {children}「ここに、そのページ自身の内容を入れてね」
// サイト全体の共通レイアウトを作って、その中に各ページを入れている
// children は、このレイアウトの中に入れる、現在のページの内容
export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookieStore = await cookies()
  const sessionId = cookieStore.get('session_id')?.value

  let isLoggedIn = false

  if (sessionId) {
    const session = await prisma.session.findUnique({
        where: { session_id: sessionId },
    })
    console.log('sessionId from cookie:', sessionId)
    console.log('session found:', session)
    isLoggedIn = !!session && session.expires_at > new Date()
}
console.log('isLoggedIn:', isLoggedIn)
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className={style.nav}>
          <span className={style.menuLabel}>menu</span>
          <div className={style.menuList}>
            {isLoggedIn ? (
              <>
                <Link href="/" className={style.navLink}>ホーム</Link>
                <Link href="/records" className={style.navLink}>記録一覧</Link>
                <Link href="/records/new" className={style.navLink}>記録をつける</Link>
                <LogoutButton />
              </>
            ) : (
              <>
                <Link href="/login" className={style.navLink}>ログイン</Link>
                <Link href="/signup" className={style.navLink}>新規登録</Link>
              </>
            )}
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}