import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import style from './layout.module.css';
import Link from "next/link";
import LogoutButton from "@/components/LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className={style.nav}>
          <span className={style.menuLabel}>menu</span>
          <Link href="/" className="app-nav-link"> ホーム </Link>
          <Link href="/records" className="app-nav-link"> 記録一覧 </Link>
          <Link href="/records/new" className="app-nav-link"> 記録をつける </Link>
          <Link href="/signup" className="app-nav-link"> 新規登録 </Link>
          <LogoutButton />
        </nav>
        {children}
      </body>
    </html>
  );
}